# Generated by Django 5.1.6 on 2025-02-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=50)),
                ('admin_email', models.EmailField(max_length=254)),
                ('contact_number', models.IntegerField()),
                ('admin_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmpDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employe_name', models.CharField(max_length=50)),
                ('employe_email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=50)),
                ('contact_number', models.IntegerField()),
                ('employe_password', models.CharField(max_length=50)),
                ('your_work', models.TextField(max_length=100)),
            ],
        ),
    ]
